### PR TITLE
Add Gleidson Nascimento as a member

### LINKED ISSUE #20: Add Gleidson Nascimento
@LorbusChris and i realized after the charter was out that firing a PR process will cause this issue however we didn't want to pull and change the charter. We'll follow up after it gets merged.

What we should have done was to ask folks to create a github issue in this repo and either @LorbusChris or i would have created the PR and merge it to avoid asking you to rebase, sorry for inconvenience ... we are learning as we go and will try to adjust/ imrpove the process

As such for tracking purpose i'll create the request here as a github issue and then i'll personally open a PR and deal with the rebase rather than asking you to fix our own problem.

Sorry for the inconvenience and support as we learning through

### PR DESCRIPTION
**Pull request by DanyC97**
Fixes #20 

ref #14

### CODE REVIEW

**Comment by DanyC97** [comment]
odd you cannot `lgtm` @LorbusChris  ...hmm

_although i know i can't review my own PR, i tried it to check bot is "sane"_ ;)

**Comment by LorbusChris** [comment]
let's try again
/lgtm

**Pull request closed without merging**
