### PR TITLE
Add initial WG members

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by LorbusChris** [comment]
or should we use a directory with a file for each member? might be easier to automate later that way. Do not want to block this approach, though.

**Comment by dustymabe** [comment]
> or should we use a directory with a file for each member? might be easier to automate later that way. Do not want to block this approach, though.

Let's go with this for now since whatever we come up with is likely to be different than either the single file or the directory approach.

**Comment by dustymabe** [comment]
also note this file isn't final - just a quick start. please open a PR to add names to the file after this has merged.

**Comment by DanyC97** [comment]
who has the permission to merge it ? i certainly don't as not being part of the openshift org

**Pull request merged**
