### PR TITLE
Add OWNERS file

### PR DESCRIPTION
**Pull request by LorbusChris**

### CODE REVIEW

**Comment by smarterclayton** [comment]
I'm running down how we get the automation properly aligned to enable contributors.  Right now we have the restrictive Kubernetes configuration from Prow that is automatically managing the group and membership.  I'm looking at how to ensure collaborators can be added to OWNERS for this repo right now.

**Comment by smarterclayton** [comment]
The mentioned folks need to accept their invites, then I will re-run

**Comment by DanyC97** [comment]
> The mentioned folks need to accept their invites, then I will re-run

~i'll do it as soon as yahoo is back online as i can't access my emails ;-(~
Thank you for taking care of this @smarterclayton , very much appreciated ! 🌟

**Comment by smarterclayton** [comment]
Let's remove klenkes74 from this PR and add him in a separate, then I can merge this.

**Comment by DanyC97** [comment]
@smarterclayton this should be good to go, once you do that i'll go and approve all the other members who created a PR so their vote counts. cheers

**Comment by smarterclayton** [comment]
I need to set up the bots against this actually

**Pull request merged**
