### PR TITLE
Call for Agreement: OKD Roadmap

### PR DESCRIPTION
**Pull request by LorbusChris**
Dear OKD Community,

this is a Call for Agreement on the topic of the OKD Roadmap, per the terms of the Charter.

Question:
**Do you _accept_ or _reject_ the proposed roadmap as the official roadmap document for OKD?**

Please comment on the pull request to indicate your vote ("_accept_" or "_reject_").

**The voting period will conclude on October 23, 2019, at 00:00 UTC.**

The outcome of the Call for Agreement will be published here as well as on the Mailing List.

Thank you for your participation.

### CODE REVIEW

**Comment by klenkes74** [comment]
accept

**Comment by vrutkovs** [comment]
accept

**Comment by Reamer** [comment]
accept

**Comment by smarterclayton** [comment]
accept

**Comment by duritong** [comment]
accept

**Comment by Conan-Kudo** [comment]
accept

**Comment by abursavich** [comment]
accept

**Comment by agno01** [comment]
accept

**Comment by sgreene570** [comment]
Accept

**Comment by dmueller2001** [comment]
accept

**Comment by JaimeMagiera** [comment]
accept

**Comment by elmiko** [comment]
accept

**Comment by Klaas-** [comment]
accept

**Comment by tdudgeon** [comment]
accept

**Comment by brian-jarvis** [comment]
accept

**Comment by cgruver** [comment]
accept

**Comment by csantanapr** [comment]
accept

**Comment by adrian555** [comment]
accept

**Comment by DanyC97** [comment]
accept

**Comment by veillard** [comment]
Can you provide link to said roadmap ?
thanks

**Comment by Klaas-** [comment]
@veillard https://github.com/openshift/community/blob/7a30fed0f15fd6933d234ca77cab0db3b5ad993b/ROADMAP.md (check files changed for this pr)

**Comment by jaywryan** [comment]
accept

**Comment by pearj** [comment]
accept

**Comment by kirankt** [comment]
Accept

**Comment by veillard** [comment]
accept

**Comment by git001** [comment]
I can't see the fact that you need a pull secret for installation, in which sentence is this included?

All over it's accepted

**Comment by vrutkovs** [comment]
>I can't see the fact that you need a pull secret for installation, in which sentence is this included?

I think this is presumed to be a part of:

>Create OpenShift CI that injects kubelet and cri-o into machine-os-content based on standard FCoS image that is publicly accessible (no auth required)

"no auth required" == "no pull secret required" here IIUC. @LorbusChris would you mind clarifying that part - and pull secret's fate in OKD?

**Comment by LorbusChris** [comment]
> "no auth required" == "no pull secret required" here IIUC. @LorbusChris would you mind clarifying that part - and pull secret's fate in OKD?

yes, exactly: No pull secret will be required.

**Comment by yu2003w** [comment]
Is that still possible to install OKD 4.x in an VLAN environment without internet access?
For OKD 3.x, we could do that by setup private image registry.

**Comment by LorbusChris** [comment]
The Roadmap has been **accepted**!

@DanyC97 could you `lgtm` this PR?

**Comment by ckaserer** [comment]
accept

**Review by klenkes74 — APPROVED** [review]

**Pull request merged**
