### PR TITLE
updated chairs

### PR DESCRIPTION
**Pull request by JaimeMagiera**
Updated the names of the chair and refined the format of the affiliation.

### CODE REVIEW

**Review by sandrobonazzola — APPROVED** [review]

**Comment by LorbusChris** [comment]
@JaimeMagiera please move my name to members (i.e not remove it entirely here)

**Review by LorbusChris — CHANGES_REQUESTED** [review]
@JaimeMagiera please move my name to members (i.e not remove it entirely here)

**Comment by JaimeMagiera** [comment]
@LorbusChris Done.

**Comment by LorbusChris** [comment]
@JaimeMagiera mind squashing the commits so we loose the merge commit here? (not strictly necessary, but it's a bit cleaner IMO)

**Comment by JaimeMagiera** [comment]
@LorbusChris squashed mine.

**Pull request merged**
